// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum HealthSpikeApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct NativeDailySteps: Hashable, CustomStringConvertible {
  /// Local calendar day, `yyyy-MM-dd`, as computed by iOS `Calendar.current`.
  var localDate: String
  var steps: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeDailySteps? {
    let localDate = pigeonVar_list[0] as! String
    let steps = pigeonVar_list[1] as! Int64

    return NativeDailySteps(
      localDate: localDate,
      steps: steps
    )
  }
  func toList() -> [Any?] {
    return [
      localDate,
      steps,
    ]
  }
  static func == (lhs: NativeDailySteps, rhs: NativeDailySteps) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return HealthSpikeApiPigeonInternal.deepEquals(lhs.localDate, rhs.localDate) && HealthSpikeApiPigeonInternal.deepEquals(lhs.steps, rhs.steps)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeDailySteps")
    HealthSpikeApiPigeonInternal.deepHash(value: localDate, hasher: &hasher)
    HealthSpikeApiPigeonInternal.deepHash(value: steps, hasher: &hasher)
  }

  public var description: String {
    return "NativeDailySteps(localDate: \(String(describing: localDate)), steps: \(String(describing: steps)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WakeupEvent: Hashable, CustomStringConvertible {
  var epochMs: Int64
  /// `active`, `inactive` or `background` at the moment the observer fired.
  var appState: String
  /// Observer error description, if any. Never contains health values.
  var error: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WakeupEvent? {
    let epochMs = pigeonVar_list[0] as! Int64
    let appState = pigeonVar_list[1] as! String
    let error: String? = nilOrValue(pigeonVar_list[2])

    return WakeupEvent(
      epochMs: epochMs,
      appState: appState,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      epochMs,
      appState,
      error,
    ]
  }
  static func == (lhs: WakeupEvent, rhs: WakeupEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return HealthSpikeApiPigeonInternal.deepEquals(lhs.epochMs, rhs.epochMs) && HealthSpikeApiPigeonInternal.deepEquals(lhs.appState, rhs.appState) && HealthSpikeApiPigeonInternal.deepEquals(lhs.error, rhs.error)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WakeupEvent")
    HealthSpikeApiPigeonInternal.deepHash(value: epochMs, hasher: &hasher)
    HealthSpikeApiPigeonInternal.deepHash(value: appState, hasher: &hasher)
    HealthSpikeApiPigeonInternal.deepHash(value: error, hasher: &hasher)
  }

  public var description: String {
    return "WakeupEvent(epochMs: \(String(describing: epochMs)), appState: \(String(describing: appState)), error: \(String(describing: error)))"
  }
}

private class HealthSpikeApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NativeDailySteps.fromList(self.readValue() as! [Any?])
    case 130:
      return WakeupEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class HealthSpikeApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeDailySteps {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? WakeupEvent {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class HealthSpikeApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return HealthSpikeApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return HealthSpikeApiPigeonCodecWriter(data: data)
  }
}

class HealthSpikeApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = HealthSpikeApiPigeonCodec(readerWriter: HealthSpikeApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HealthSpikeHostApi {
  /// Daily step totals via HKStatisticsCollectionQuery (deduplicated by
  /// HealthKit), for the last [days] local days including today.
  func dailySteps(days: Int64) async throws -> [NativeDailySteps]
  /// Moments when HKObserverQuery fired, oldest first.
  func wakeups() throws -> [WakeupEvent]
  func clearWakeups() throws
  /// (Re)registers the observer query and background delivery. Called on
  /// launch natively, and from Dart right after authorization is granted.
  func startObserving() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HealthSpikeHostApiSetup {
  static var codec: FlutterStandardMessageCodec { HealthSpikeApiPigeonCodec.shared }
  /// Sets up an instance of `HealthSpikeHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HealthSpikeHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Daily step totals via HKStatisticsCollectionQuery (deduplicated by
    /// HealthKit), for the last [days] local days including today.
    let dailyStepsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.shlyakh.HealthSpikeHostApi.dailySteps\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      dailyStepsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let daysArg = args[0] as! Int64
        Task { @MainActor in
          do {
            let result = try await api.dailySteps(days: daysArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      dailyStepsChannel.setMessageHandler(nil)
    }
    /// Moments when HKObserverQuery fired, oldest first.
    let wakeupsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.shlyakh.HealthSpikeHostApi.wakeups\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      wakeupsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.wakeups()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      wakeupsChannel.setMessageHandler(nil)
    }
    let clearWakeupsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.shlyakh.HealthSpikeHostApi.clearWakeups\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearWakeupsChannel.setMessageHandler { _, reply in
        do {
          try api.clearWakeups()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearWakeupsChannel.setMessageHandler(nil)
    }
    /// (Re)registers the observer query and background delivery. Called on
    /// launch natively, and from Dart right after authorization is granted.
    let startObservingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.shlyakh.HealthSpikeHostApi.startObserving\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startObservingChannel.setMessageHandler { _, reply in
        do {
          try api.startObserving()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startObservingChannel.setMessageHandler(nil)
    }
  }
}
