// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum StepsApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// One local day's step total.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeDay: Hashable, CustomStringConvertible {
  /// `yyyy-MM-dd` in the device's current calendar and time zone.
  var localDate: String
  /// Deduplicated by HealthKit, fractional steps truncated.
  var steps: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeDay? {
    let localDate = pigeonVar_list[0] as! String
    let steps = pigeonVar_list[1] as! Int64

    return NativeDay(
      localDate: localDate,
      steps: steps
    )
  }
  func toList() -> [Any?] {
    return [
      localDate,
      steps,
    ]
  }
  static func == (lhs: NativeDay, rhs: NativeDay) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return StepsApiPigeonInternal.deepEquals(lhs.localDate, rhs.localDate) && StepsApiPigeonInternal.deepEquals(lhs.steps, rhs.steps)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeDay")
    StepsApiPigeonInternal.deepHash(value: localDate, hasher: &hasher)
    StepsApiPigeonInternal.deepHash(value: steps, hasher: &hasher)
  }

  public var description: String {
    return "NativeDay(localDate: \(String(describing: localDate)), steps: \(String(describing: steps)))"
  }
}

private class StepsApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NativeDay.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class StepsApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeDay {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class StepsApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return StepsApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return StepsApiPigeonCodecWriter(data: data)
  }
}

class StepsApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = StepsApiPigeonCodec(readerWriter: StepsApiPigeonCodecReaderWriter())
}


/// Calls from Dart into HealthKit. Errors carry the codes `unavailable`,
/// `locked` or `healthkit` and never a message.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol StepsHostApi {
  /// Whether HealthKit is available on this device.
  func isAvailable() throws -> Bool
  /// Shows the system prompt for read access to step count. Completes
  /// without saying what the user chose: iOS never tells.
  func requestAccess() async throws
  /// Every local day from [fromEpochMs] to the end of today, oldest first;
  /// the first day is partial when [fromEpochMs] is not a local midnight.
  func dailySteps(fromEpochMs: Int64) async throws -> [NativeDay]
  /// The device's IANA time zone identifier, e.g. `Europe/Kyiv`.
  func timeZoneId() throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class StepsHostApiSetup {
  static var codec: FlutterStandardMessageCodec { StepsApiPigeonCodec.shared }
  /// Sets up an instance of `StepsHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: StepsHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Whether HealthKit is available on this device.
    let isAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.shlyakh.StepsHostApi.isAvailable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isAvailableChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isAvailable()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isAvailableChannel.setMessageHandler(nil)
    }
    /// Shows the system prompt for read access to step count. Completes
    /// without saying what the user chose: iOS never tells.
    let requestAccessChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.shlyakh.StepsHostApi.requestAccess\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestAccessChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            try await api.requestAccess()
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestAccessChannel.setMessageHandler(nil)
    }
    /// Every local day from [fromEpochMs] to the end of today, oldest first;
    /// the first day is partial when [fromEpochMs] is not a local midnight.
    let dailyStepsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.shlyakh.StepsHostApi.dailySteps\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      dailyStepsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let fromEpochMsArg = args[0] as! Int64
        Task { @MainActor in
          do {
            let result = try await api.dailySteps(fromEpochMs: fromEpochMsArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      dailyStepsChannel.setMessageHandler(nil)
    }
    /// The device's IANA time zone identifier, e.g. `Europe/Kyiv`.
    let timeZoneIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.shlyakh.StepsHostApi.timeZoneId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      timeZoneIdChannel.setMessageHandler { _, reply in
        do {
          let result = try api.timeZoneId()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      timeZoneIdChannel.setMessageHandler(nil)
    }
  }
}

/// Calls from HealthKit's observer into Dart.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol StepsEventsApiProtocol {
  /// New step data exists. Completes when Dart has finished its sync.
  @MainActor func onStepsChanged() async throws
}
class StepsEventsApi: StepsEventsApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: StepsApiPigeonCodec {
    return StepsApiPigeonCodec.shared
  }
  /// New step data exists. Completes when Dart has finished its sync.
  @MainActor func onStepsChanged() async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.shlyakh.StepsEventsApi.onStepsChanged\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage(nil) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
