// Builds assets/sky/route.json from d3-celestial at a pinned commit
// (docs/decisions/0009-sky-data.md).
//
// Usage: dart run tool/sky/build_route.dart
//
// Downloads are cached in .dart_tool/sky/ and never committed. The build
// fails when a constellation's star count differs from the spec
// (docs/superpowers/specs/2026-09-28-constellation-path-design.md).
import 'dart:convert';
import 'dart:io';

import 'sky.dart';

const _repo = 'ofrohn/d3-celestial';
const _sha = '7e720a3de062059d4c5400a379146a601d9010e0';
const _files = ['data/constellations.lines.json', 'data/stars.6.json'];

const _mainRoute = [
  'Sge', 'Vul', 'Cyg', 'Lac', 'Cep', 'Cas', 'Per', //
  'Aur', 'Tau', 'Gem', 'Ori', 'Mon', 'CMa',
];
const _branch = ['Aql', 'Sct', 'Sgr'];

/// Figure star counts from the spec; the build fails on any difference.
const _expectedStars = {
  'Sge': 4, 'Vul': 5, 'Cyg': 9, 'Lac': 9, 'Cep': 10, 'Cas': 5, //
  'Per': 23, 'Aur': 9, 'Tau': 12, 'Gem': 12, 'Ori': 23, 'Mon': 9,
  'CMa': 11, 'Aql': 8, 'Sct': 4, 'Sgr': 25,
};

Future<void> main() async {
  final lines = await _download(_files[0]);
  final stars = await _download(_files[1]);
  final figures = parseFigures(lines);
  final catalogue = parseStars(stars);

  final ids = [..._mainRoute, ..._branch]..sort();
  final Map<String, RouteConstellation> route;
  try {
    route = buildRoute(figures, catalogue, ids);
  } on SkyDataException catch (e) {
    stderr.writeln('Sky build failed: ${e.message}');
    exit(1);
  }

  final constellations = <String, Object>{};
  final mismatches = <String>[];
  for (final id in ids) {
    final c = route[id]!;
    final figure = c.figure;
    if (figure.stars.length != _expectedStars[id]) {
      mismatches.add(
        '$id: expected ${_expectedStars[id]}, got ${figure.stars.length}',
      );
    }
    final points = project(figure.stars);
    constellations[id] = {
      'centre': {'dec': c.centre.dec, 'ra': c.centre.ra},
      'lines': [
        for (final (a, b) in figure.lines) [a, b],
      ],
      'order': figure.lightingOrder,
      'spanDeg': c.spanDeg,
      'stars': [
        for (final (i, star) in figure.stars.indexed)
          {
            'dec': star.dec,
            'hip': star.hip,
            'mag': star.mag,
            'ra': star.ra,
            'x': points[i].$1,
            'y': points[i].$2,
          },
      ],
    };
  }
  if (mismatches.isNotEmpty) {
    stderr.writeln(
      'Star counts differ from the spec:\n${mismatches.join('\n')}',
    );
    exit(1);
  }

  final asset = {
    'constellations': constellations,
    'route': {'branch': _branch, 'main': _mainRoute},
    'source': {'files': _files, 'repo': _repo, 'sha': _sha},
  };
  Directory('assets/sky').createSync(recursive: true);
  File(
    'assets/sky/route.json',
  ).writeAsStringSync('${const JsonEncoder.withIndent('  ').convert(asset)}\n');
  File('assets/sky/SOURCES.md').writeAsStringSync(_sources());
  stdout.writeln('Wrote ${constellations.length} constellations.');
}

Future<String> _download(String path) async {
  final cache = File('.dart_tool/sky/$_sha/$path');
  if (cache.existsSync()) return cache.readAsStringSync();
  final url = Uri.parse('https://raw.githubusercontent.com/$_repo/$_sha/$path');
  final client = HttpClient();
  try {
    final response = await (await client.getUrl(url)).close();
    if (response.statusCode != 200) {
      throw HttpException('HTTP ${response.statusCode}', uri: url);
    }
    final body = await response.transform(utf8.decoder).join();
    cache.parent.createSync(recursive: true);
    cache.writeAsStringSync(body);
    return body;
  } finally {
    client.close();
  }
}

String _sources() =>
    '''
# Sky data sources

Generated by `tool/sky/build_route.dart`; do not edit by hand
(docs/decisions/0009-sky-data.md).

- Repository: https://github.com/$_repo at commit `$_sha`
${[for (final f in _files) '- https://raw.githubusercontent.com/$_repo/$_sha/$f'].join('\n')}
- Licence: BSD-3-Clause, © Olaf Frohn (d3-celestial).
- Constellation figures: IAU and Sky & Telescope (CC BY 4.0), with line
  modifications by the d3-celestial author.
- Star positions and magnitudes: XHIP (Anderson & Francis 2012), via
  d3-celestial. Positions are J2000 right ascension and declination in
  degrees.
''';
